force-app/main/default/objects/Protected_Campaign_Status__mdt/Protected_Campaign_Status__mdt.object-meta.xml
<CustomObject>
    <label>Protected Campaign Status</label>
    <pluralLabel>Protected Campaign Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>The Campaign&apos;s Type (not record type) for this Protected Status</description>
    <label>Campaign Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Is_Responded__c.field-meta.xml
<CustomField>
    <fullName>Is_Responded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Responded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/New_Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>New_Campaign_Member_Status__c</fullName>
    <label>New Campaign Member Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SL_ProtectedCampaignServiceData.cls
@isTest
public class SL_ProtectedCampaignServiceData {
    public static Protected_Campaign_Status__mdt newDefaultStatus(String type, String name) {
        return build(type, name, true, false);
    }

    public static Protected_Campaign_Status__mdt newRespondedStatus(String type, String name) {
        return build(type, name, false, true);
    }

    public static Protected_Campaign_Status__mdt newDefaultAndRespondedStatus(String type, String name) {
        return build(type, name, true, true);
    }

    public static Protected_Campaign_Status__mdt newStatus(String type, String name) {
        return build(type, name, false, false);
    }

    private static Protected_Campaign_Status__mdt build(String type, String name, Boolean defaultStatus, Boolean respondedStatus) {
        Protected_Campaign_Status__mdt item = new Protected_Campaign_Status__mdt();
        item.Label = type+'-'+name;
        item.DeveloperName = item.Label.replace(' ','_').replace('-','_');
        item.Campaign_Type__c = type;
        item.New_Campaign_Member_Status__c = name;
        item.Is_Default__c = defaultStatus;
        item.Is_Responded__c = respondedStatus;
        return item;
    }

    public class SL_WebinarMock extends SL_ProtectedCampaignRepository {
        private final List<Protected_Campaign_Status__mdt> values;

        public SL_WebinarMock(List<Protected_Campaign_Status__mdt> values) {
            this.values=values;
        }
    
        public override Map<String, List<Protected_Campaign_Status__mdt>> getGroupedProtectedStatuses() {
            System.debug('overriding actually getting MDTs from Salesforce, using hard coded Webinar MDTs');
            Map<String, List<Protected_Campaign_Status__mdt>> response = new Map<String, List<Protected_Campaign_Status__mdt>>();
            response.put(values.get(0).Campaign_Type__c, values);
            return response;
        }
    }
}