force-app/main/default/objects/Protected_Campaign_Status__mdt/Protected_Campaign_Status__mdt.object-meta.xml
<CustomObject>
    <label>Protected Campaign Status</label>
    <pluralLabel>Protected Campaign Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>The Campaign&apos;s Type (not record type) for this Protected Status</description>
    <label>Campaign Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Is_Responded__c.field-meta.xml
<CustomField>
    <fullName>Is_Responded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Responded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/New_Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>New_Campaign_Member_Status__c</fullName>
    <label>New Campaign Member Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Protected_Campaign_Status__mdt/fields/Original_Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Original_Campaign_Member_Status__c</fullName>
    <label>Original Campaign Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Responded</fullName>
                <default>true</default>
                <label>Responded</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SL_ProtectedCampaignRepository.cls
public without sharing virtual class SL_ProtectedCampaignRepository {

    public virtual Map<String, List<Protected_Campaign_Status__mdt>> getGroupedProtectedStatuses() {
        List<Protected_Campaign_Status__mdt> protectedStatuses = [
            SELECT Label, Campaign_Type__c, Original_Campaign_Member_Status__c, New_Campaign_Member_Status__c, Is_Default__c, Is_Responded__c 
            FROM Protected_Campaign_Status__mdt
            ORDER BY Campaign_Type__c, Is_Default__c DESC, Is_Responded__c DESC];

        Map<String, List<Protected_Campaign_Status__mdt>> groupedProtectedStatuses = new Map<String, List<Protected_Campaign_Status__mdt>>();
        for(Protected_Campaign_Status__mdt status : protectedStatuses) {
            if(!groupedProtectedStatuses.containsKey(status.Campaign_Type__c)) {
                groupedProtectedStatuses.put(status.Campaign_Type__c, new List<Protected_Campaign_Status__mdt>());
            }
            groupedProtectedStatuses.get(status.Campaign_Type__c).add(status);
        }
        return groupedProtectedStatuses;
    }
}